thislist = input("Enter some numbers: ").split(",")
newlist = list(map(int, thislist))
print("Max: " + str(max(newlist)))
print("Min: " + str(min(newlist)))
summa = sum(newlist)
print("Sum: " + str(summa))
