thislist = input("Enter some numbers: ").split(",")
newlist = list(map(int, thislist))
print("Max: " + str(max(newlist)))
print("Min: " + str(min(newlist)))
newlist.sort()
print(newlist)
summa = sum(newlist[1: -1])
print("Sum: " + str(summa))
